# Generated by Django 5.2 on 2025-11-05 16:28

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('url', models.URLField()),
                ('avatar_url', models.URLField()),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_commits', models.IntegerField(default=0)),
                ('total_issues_closed', models.IntegerField(default=0)),
                ('total_prs_reviewed', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('experience_points', models.IntegerField(default=0)),
                ('preferred_work_hours', models.CharField(blank=True, max_length=50, null=True)),
                ('activity_streak', models.IntegerField(default=0)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('coding_pattern', models.JSONField(blank=True, default=dict)),
                ('skill_tags', models.JSONField(blank=True, default=list)),
                ('burnout_risk_score', models.FloatField(default=0.0)),
                ('collaboration_score', models.FloatField(default=0.0)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-total_score', '-level'],
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('avatar_url', models.URLField()),
                ('url', models.URLField()),
                ('summary', models.TextField()),
                ('raw_data', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stars', models.IntegerField(default=0)),
                ('forks', models.IntegerField(default=0)),
                ('open_issues', models.IntegerField(default=0)),
                ('health_score', models.FloatField(default=0.0)),
                ('activity_trend', models.CharField(default='stable', max_length=20)),
                ('primary_language', models.CharField(blank=True, max_length=100, null=True)),
                ('predicted_completion_date', models.DateField(blank=True, null=True)),
                ('velocity_score', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name_plural': 'Repositories',
                'ordering': ['-stars'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('bio', models.TextField(blank=True, null=True)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('github_username', models.CharField(blank=True, max_length=255, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('total_repositories', models.IntegerField(default=0)),
                ('total_commits', models.IntegerField(default=0)),
                ('total_contributions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='RepositoryWork',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commit_count', models.IntegerField(default=0)),
                ('issue_count', models.IntegerField(default=0)),
                ('lines_added', models.IntegerField(default=0)),
                ('lines_removed', models.IntegerField(default=0)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='api.contributor')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='api.repository')),
            ],
            options={
                'unique_together': {('repository', 'contributor')},
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('raw_data', models.JSONField()),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(default='open', max_length=20)),
                ('is_bug', models.BooleanField(default=False)),
                ('is_feature', models.BooleanField(default=False)),
                ('priority', models.CharField(default='medium', max_length=20)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='api.repositorywork')),
            ],
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('raw_data', models.JSONField()),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('additions', models.IntegerField(default=0)),
                ('deletions', models.IntegerField(default=0)),
                ('files_changed', models.IntegerField(default=0)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('code_churn_ratio', models.FloatField(default=0.0)),
                ('contributor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='api.contributor')),
                ('repository', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='api.repository')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='api.repositorywork')),
            ],
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('badge_type', models.CharField(choices=[('early_bird', '🌅 Early Bird'), ('night_owl', '🦉 Night Owl'), ('bug_hunter', '🐛 Bug Hunter'), ('feature_master', '⭐ Feature Master'), ('code_reviewer', '👀 Code Reviewer'), ('streak_master', '🔥 Streak Master'), ('team_player', '🤝 Team Player'), ('innovator', '💡 Innovator'), ('consistent', '📊 Consistent Contributor'), ('speedster', '⚡ Speedster')], max_length=50)),
                ('earned_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='api.contributor')),
            ],
            options={
                'ordering': ['-earned_date'],
                'unique_together': {('contributor', 'badge_type')},
            },
        ),
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shared_commits', models.IntegerField(default=0)),
                ('code_reviews', models.IntegerField(default=0)),
                ('issue_discussions', models.IntegerField(default=0)),
                ('collaboration_strength', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contributor_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations_from', to='api.contributor')),
                ('contributor_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations_to', to='api.contributor')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to='api.repository')),
            ],
            options={
                'unique_together': {('contributor_1', 'contributor_2', 'repository')},
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('commit', 'Commit'), ('issue_created', 'Issue Created'), ('issue_closed', 'Issue Closed'), ('pr_opened', 'PR Opened'), ('pr_reviewed', 'PR Reviewed'), ('comment', 'Comment')], max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.contributor')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.repository')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['contributor', '-timestamp'], name='api_activit_contrib_43d020_idx'), models.Index(fields=['repository', '-timestamp'], name='api_activit_reposit_0dbdc4_idx')],
            },
        ),
    ]
