# Generated by Django 5.2 on 2025-11-08 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_repository_change_failure_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubAppInstallation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('installation_id', models.BigIntegerField(unique=True)),
                ('account_login', models.CharField(blank=True, max_length=255, null=True)),
                ('account_type', models.CharField(blank=True, max_length=50, null=True)),
                ('account_avatar_url', models.URLField(blank=True, null=True)),
                ('target_type', models.CharField(blank=True, max_length=50, null=True)),
                ('setup_action', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_installations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='api_githuba_user_id_2c6cb7_idx'), models.Index(fields=['installation_id'], name='api_githuba_install_3fdb87_idx')],
            },
        ),
    ]
