# Generated by Django 5.2.7 on 2025-11-08 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_repository_change_failure_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('planned_velocity', models.IntegerField(default=0)),
                ('actual_velocity', models.IntegerField(default=0)),
                ('total_issues', models.IntegerField(default=0)),
                ('completed_issues', models.IntegerField(default=0)),
                ('team_capacity', models.IntegerField(default=0)),
                ('allocated_hours', models.IntegerField(default=0)),
                ('ai_suggested', models.BooleanField(default=False)),
                ('suggestion_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sprints', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='api.organization')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='api.repository')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sprints', to='api.team')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='SprintIssue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('issue_type', models.CharField(default='task', max_length=50)),
                ('story_points', models.IntegerField(default=0)),
                ('estimated_hours', models.FloatField(default=0.0)),
                ('actual_hours', models.FloatField(blank=True, default=0.0, null=True)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('blocked', 'Blocked')], default='todo', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('ai_assigned', models.BooleanField(default=False)),
                ('ai_reasoning', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to='api.contributor')),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprint_assignments', to='api.issue')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprint_issues', to='api.sprint')),
            ],
            options={
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SprintVelocityHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('planned_velocity', models.IntegerField(default=0)),
                ('actual_velocity', models.IntegerField(default=0)),
                ('team_size', models.IntegerField(default=0)),
                ('total_issues', models.IntegerField(default=0)),
                ('completed_issues', models.IntegerField(default=0)),
                ('completion_rate', models.FloatField(default=0.0)),
                ('planned_hours', models.FloatField(default=0.0)),
                ('actual_hours', models.FloatField(default=0.0)),
                ('sprint_start', models.DateField()),
                ('sprint_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='velocity_history', to='api.repository')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='velocity_records', to='api.sprint')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='velocity_history', to='api.team')),
            ],
            options={
                'ordering': ['-sprint_start'],
            },
        ),
        migrations.CreateModel(
            name='TeamMemberCapacity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_capacity_hours', models.FloatField(default=40.0)),
                ('allocated_hours', models.FloatField(default=0.0)),
                ('availability_percentage', models.FloatField(default=100.0)),
                ('time_off_hours', models.FloatField(default=0.0)),
                ('other_commitments_hours', models.FloatField(default=0.0)),
                ('average_velocity', models.FloatField(default=0.0)),
                ('average_hours_per_point', models.FloatField(default=4.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprint_capacities', to='api.contributor')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_capacities', to='api.sprint')),
            ],
            options={
                'ordering': ['contributor__username'],
            },
        ),
        migrations.AddIndex(
            model_name='sprint',
            index=models.Index(fields=['repository', 'status'], name='api_sprint_reposit_102a76_idx'),
        ),
        migrations.AddIndex(
            model_name='sprint',
            index=models.Index(fields=['start_date', 'end_date'], name='api_sprint_start_d_07d534_idx'),
        ),
        migrations.AddIndex(
            model_name='sprintissue',
            index=models.Index(fields=['sprint', 'status'], name='api_sprinti_sprint__2a4cc8_idx'),
        ),
        migrations.AddIndex(
            model_name='sprintissue',
            index=models.Index(fields=['assigned_to', 'status'], name='api_sprinti_assigne_9dcda5_idx'),
        ),
        migrations.AddIndex(
            model_name='sprintvelocityhistory',
            index=models.Index(fields=['repository', '-sprint_start'], name='api_sprintv_reposit_150a7d_idx'),
        ),
        migrations.AddIndex(
            model_name='sprintvelocityhistory',
            index=models.Index(fields=['team', '-sprint_start'], name='api_sprintv_team_id_5f1a4b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teammembercapacity',
            unique_together={('sprint', 'contributor')},
        ),
    ]
