# Generated by Django 5.2 on 2025-11-08 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_githubappinstallation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncJob',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('auto_import', 'Auto Import'), ('periodic_sync', 'Periodic Sync'), ('manual_sync', 'Manual Sync'), ('webhook_triggered', 'Webhook Triggered')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('completed_with_errors', 'Completed with Errors'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('repositories_processed', models.IntegerField(default=0)),
                ('errors_count', models.IntegerField(default=0)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='commit',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commit',
            name='sha',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='github_issue_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='auto_sync_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='github_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='installation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='api.githubappinstallation'),
        ),
        migrations.AddField(
            model_name='repository',
            name='language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='webhook_configured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='githubappinstallation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='github_installations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='commit',
            index=models.Index(fields=['sha'], name='api_commit_sha_2a1ffe_idx'),
        ),
        migrations.AddIndex(
            model_name='commit',
            index=models.Index(fields=['work'], name='api_commit_work_id_4e265d_idx'),
        ),
        migrations.AddIndex(
            model_name='commit',
            index=models.Index(fields=['committed_at'], name='api_commit_committ_900baa_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['github_issue_id'], name='api_issue_github__e878d0_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['state'], name='api_issue_state_d63f05_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['work'], name='api_issue_work_id_7de096_idx'),
        ),
        migrations.AddIndex(
            model_name='repository',
            index=models.Index(fields=['github_id'], name='api_reposit_github__4ddeaf_idx'),
        ),
        migrations.AddIndex(
            model_name='repository',
            index=models.Index(fields=['installation'], name='api_reposit_install_24bf9e_idx'),
        ),
        migrations.AddIndex(
            model_name='repository',
            index=models.Index(fields=['last_synced_at'], name='api_reposit_last_sy_083481_idx'),
        ),
        migrations.AddField(
            model_name='syncjob',
            name='installation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_jobs', to='api.githubappinstallation'),
        ),
        migrations.AddIndex(
            model_name='syncjob',
            index=models.Index(fields=['installation'], name='api_syncjob_install_985a2a_idx'),
        ),
        migrations.AddIndex(
            model_name='syncjob',
            index=models.Index(fields=['job_type'], name='api_syncjob_job_typ_270c0e_idx'),
        ),
        migrations.AddIndex(
            model_name='syncjob',
            index=models.Index(fields=['status'], name='api_syncjob_status_eeb7b8_idx'),
        ),
        migrations.AddIndex(
            model_name='syncjob',
            index=models.Index(fields=['-started_at'], name='api_syncjob_started_75efdc_idx'),
        ),
    ]
