# Generated by Django 5.2.7 on 2025-11-09 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_sprint_sprintissue_sprintvelocityhistory_and_more'),
        ('api', '0004_syncjob_commit_message_commit_sha_issue_body_and_more'),
    ]

    operations = [
    ]
