# Generated by Django 5.2 on 2025-11-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_syncjob_commit_message_commit_sha_issue_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='default_branch',
            field=models.CharField(default='main', max_length=100),
        ),
        migrations.AddField(
            model_name='repository',
            name='is_local',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='repository',
            name='local_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
