# Generated by Django 5.2.7 on 2025-11-09 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_local_git_support'),
        ('api', '0005_merge_20251109_0609'),
    ]

    operations = [
    ]
